version: '3'
services:
  kitchen:
    build:
      context: ./kitchen
    ports:
      - "8080:8080"
    depends_on:
      - store

  store:
    build:
      context: ./store
    ports:
      - "8081:8081"

