services:
  kitchen:
    build:
      context: ./kitchen
    ports:
      - "8080:8080"
    depends_on:
      - store
    volumes:
      - ./database/data:/app/data.db

  store:
    build:
      context: ./store
    ports:
      - "8081:8081"
    volumes:
      - ./database/data:/app/data.db
